
sequences: /cluster/project/beltrao/jjaenes/22.05.30_alphafold_on_euler/openfold/examples/MAPK1_DUSP6/MAPK1_DUSP6.txt

openfold_dir: /cluster/work/beltrao/jjaenes/24.06.10_af2genomics/software/openfold

base_data_dir: /cluster/project/alphafold
template_mmcif_dir: /cluster/project/alphafold/pdb_mmcif/mmcif_files/
uniref90_database_path: --uniref90_database_path /cluster/project/alphafold/uniref90/uniref90.fasta
mgnify_database_path: --mgnify_database_path /cluster/project/alphafold/mgnify/mgy_clusters_2018_12.fa
pdb_seqres_database_path: --pdb_seqres_database_path /cluster/project/alphafold/pdb_seqres/pdb_seqres.txt
uniref30_database_path: --uniref30_database_path /cluster/project/alphafold/uniref30/UniRef30_2021_03
uniprot_database_path:  --uniprot_database_path /cluster/project/alphafold/uniprot/uniprot.fasta
bfd_database_path: --bfd_database_path /cluster/project/alphafold/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt
binary_paths: --jackhmmer_binary_path jackhmmer --hhblits_binary_path hhblits --hmmsearch_binary_path hmmsearch --hmmbuild_binary_path hmmbuild --kalign_binary_path kalign

max_template_date:
  no_templates: --max_template_date '1950-01-01'
  Evans2022: --max_template_date '2018-04-30'
