# Runtime series (one for each euler queue):
#     runtime: f"{['4h', '1d', '3d', '1w'][attempt - 1]}"
#
# Sizes for mem_mb/disk_mb:
#      64g: 65536
#     128g: 131072
#     256g: 262144
#     512g: 524288
#
# One GPU, increasing memory:
#     slurm_extra: f"{[ '--gpus=1 --gres=gpumem%11g', '--gpus=1 --gres=gpumem%24g', '--gpus=1 --gres=gpumem%32g', '--gpus=1 --gres=gpumem%40g', '--gpus=1 --gres=gpumem%80g', ][attempt - 1]}"
#
# Specific models:
#     slurm_extra: "'--gpus=rtx_3090%1 --gres=gpumem%11g'"
#     slurm_extra: "'--gpus=rtx_2080_ti%1 --gres=gpumem%11g'"
#     slurm_extra: "'--gpus=rtx_4090%3A1 --gres=gpumem%3A24g'"
#
# Ref: https://scicomp.ethz.ch/wiki/Getting_started_with_GPUs#Available_GPU_node_types
set-threads:
  - colabfold_search=16
  - colabfold_batch=1
  - helixfold3_run_infer=4
  - openfold_precompute_alignments=8
  - openfold_run_multimer=4
  - openfold_run_unit_tests=4
  - openfold_setup=4
set-resources:
  colabfold_setup_databases:
    runtime: 3d
    mem_mb: 131072
    disk_mb: 131072
  colabfold_search:
    runtime: 1d
    mem_mb: 262144
    disk_mb: 262144
  colabfold_batch:
    runtime: 3d
    mem_mb: 262144
    disk_mb: 262144
    slurm_extra: f"{[ '--gpus=1 --gres=gpumem%24g', '--gpus=1 --gres=gpumem%32g', '--gpus=1 --gres=gpumem%40g', '--gpus=1 --gres=gpumem%80g', ][attempt - 1]}"
  helixfold3_run_infer:
    runtime: 4h
    mem_mb: 65536
    disk_mb: 65536
    slurm_extra: f"{[ '--gpus=1 --gres=gpumem%32g', '--gpus=1 --gres=gpumem%40g', '--gpus=1 --gres=gpumem%80g', ][attempt - 1]}"
  openfold_precompute_alignments:
    runtime: 1d
    mem_mb: 32768
    disk_mb: 32768
  openfold_run_multimer:
    runtime: 4h
    mem_mb: 65536
    disk_mb: 65536
    slurm_extra: f"{[ '--gpus=1 --gres=gpumem%32g', '--gpus=1 --gres=gpumem%40g', '--gpus=1 --gres=gpumem%80g', ][attempt - 1]}"
  openfold_run_unit_tests:
    runtime: 1h
    mem_mb: 131072
    disk_mb: 131072
    slurm_extra: "'--gpus=1 --gres=gpumem%11g'"
  openfold_setup:
    runtime: 1h
    mem_mb: 131072
    disk_mb: 131072
    slurm_extra: "'--gpus=1 --gres=gpumem%11g'"
use-conda: True
use-envmodules: True
use-singularity: True
singularity-args: "--nv -B $HOME,$PROJECT,$WORK,$TMPDIR"
restart-times: 0
