set-threads:
  - precompute_alignments=8
  - run_pretrained_openfold_multimer=8
set-resources:
  precompute_alignments:
    mem_mb: 131072
    disk_mb: 131072
  run_multimer:
    mem_mb: 131072
    disk_mb: 131072
    # https://scicomp.ethz.ch/wiki/Getting_started_with_GPUs#Available_GPU_node_types
    slurm_extra: "'--gpus=rtx_4090%3A1 --gres=gpumem%3A24g'"
    #slurm_extra: "'--gpus=1 --gres=gpumem%3A40g'"
  run_unit_tests:
    mem_mb: 131072
    disk_mb: 131072
    #slurm_extra: "'--gpus=1 --gres=gpumem%3A16g'"
    slurm_extra: "'--gpus=rtx_4090%3A1 --gres=gpumem%3A24g'"
