# https://scicomp.ethz.ch/wiki/Getting_started_with_GPUs#Available_GPU_node_types
set-threads:
  - precompute_alignments=4
  - run_multimer=4
  - run_unit_tests=4
  - openfold_setup=4
set-resources:
  precompute_alignments:
    mem_mb: 131072
    disk_mb: 131072
  run_multimer:
    mem_mb: 131072
    disk_mb: 131072
    slurm_extra: "'--gpus=rtx_3090%1 --gres=gpumem%11g'"
    #slurm_extra: "'--gpus=rtx_2080_ti%1 --gres=gpumem%11g'"
    #slurm_extra: "'--gpus=1 --gres=gpumem%3A24g'"
    #slurm_extra: "'--gpus=rtx_4090%3A1 --gres=gpumem%3A24g'"
  run_unit_tests:
    runtime: 1h
    mem_mb: 131072
    disk_mb: 131072
    slurm_extra: "'--gpus=1 --gres=gpumem%16g'"
    #slurm_extra: "'--gpus=rtx_4090%3A1 --gres=gpumem%3A24g'"
  openfold_setup:
    runtime: 1h
    mem_mb: 131072
    disk_mb: 131072
    slurm_extra: "'--gpus=1 --gres=gpumem%16g'"
    #slurm_extra: "'--gpus=rtx_4090%3A1 --gres=gpumem%3A24g'"
use-conda: True
use-envmodules: True
restart-times: 0
